export const ActionTypes = {
    INIT: "INIT",
    CREATEPRODUCT_PENDING: "CREATEPRODUCT_PENDING",
    CREATEPRODUCT_FULFILLED: "CREATEPRODUCT_FULFILLED",
    CREATEPRODUCT_REJECTED: "CREATEPRODUCT_REJECTED",
    LOGOUT: "LOGOUT",
};
