export enum IconName {
  HEART = "HEART",
  EDIT = "EDIT",
  DELETE = "DELETE",
  CLOSE = "CLOSE",
  LOGOUT="LOGOUT",
  HOME="HOME",
  ADDUSER="ADDUSER",
  USERLIST="USERLIST",
  SETTING="SETTING",
  INFO="INFO",
  CONTACT="CONTACT",
  PRODUCT="PRODUCT",
  PRODUCTLIST="PRODUCTLIST"
}